##exploring dataframes

In [2]:
import pandas as pd

In [3]:
#iris dataset
iris=pd.read_csv('Iris.csv')

In [4]:
iris.head()     #species of a flower

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
#select a column
iris['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [6]:
iris.SepalLengthCm

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [7]:
iris['SepalLengthCm'].max()

7.9

In [8]:
iris['SepalLengthCm'].min()

4.3

In [9]:
iris[['SepalLengthCm','PetalLengthCm']].min()

SepalLengthCm    4.3
PetalLengthCm    1.0
dtype: float64

In [10]:
#add a new column
iris['new_column']=iris['PetalLengthCm']+iris['SepalLengthCm']

In [11]:
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,new_column
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,2,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,3,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4

In [16]:
#drop the columns
iris=iris.drop('new_column',axis=1)

In [17]:
#drop rows
iris.drop([0],inplace=True)

In [18]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [19]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [20]:
iris['Species'].nunique()

3

In [22]:
iris['SepalLengthCm'].count()

149

In [23]:
iris['Species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: Species, dtype: int64

In [ ]:
#filtering

In [25]:
iris[iris['Species']=='Iris-setosa']

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [26]:
iris[(iris['Species']=='Iris-setosa')&(iris['PetalLengthCm']>1.6)]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
5    6            5.4           3.9            1.7           0.4  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa

In [28]:
#filtering using lists
length=[3.3,3,3.4]
iris[iris['SepalWidthCm'].isin(length)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
39,40,5.1,3.4,1.5,0.2,Iris-setosa
45,46,4.8,3.0,1.4,0.3,Iris-setosa
49,50,5.0,3.3,1.4,0.2,Iris-setosa
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor
91,92,6.1,3.0,4.6,1.4,Iris-versicolor
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica